### PR TITLE
Paths with spaces need to be escaped on Windows

### PR DESCRIPTION
**Pull request by marcodiiga**
On Windows the `conanfile_directory` path needs to be either quoted or escaped if it contains spaces.

### CODE REVIEW

**Comment by memsharded** [comment]
Hi @marcodiiga !

Thanks for trying to improve this, and sorry I have been busy and couldn't look it before. Having a look now.

**Comment by memsharded** [comment]
I have been investigating. It was very weird that the CI builds broke, without actually changing anything related. What I have found:

- The CI servers have upgraded, so the default libstdc++ has upgraded to libstdc++11 in some servers
- There is also a bug in ``ConfigureEnvironment`` that fails to adequately handle ``libcxx``. So the build is getting link errors due to incompatibility between libstdc++ in the protobuf library and the app. I have open an issue to solve it: https://github.com/conan-io/conan/issues/791

Tomorrow I will keep working on this. Cheers!

**Comment by memsharded** [comment]
Some more progress:

We have released today conan 0.17.2 minor release to solve that ConfigureEnvironment bug. I have relaunched travis CI and it seems things have improved: https://travis-ci.org/memsharded/conan-protobuf/builds/157754493. Now, the Linux build is not broken (as it was before your PR, your PR was failing CI but not due to the PR, but such a failure plus the upgrade of CI infrastructure).

Tomorrow I will try to merge your PR, add a few improvements and push everything. Thanks again for your help!

**Comment by marcodiiga** [comment]
Thanks for looking into this in the first place 👍

**Comment by memsharded** [comment]
Finally, I manage to get a green build! Then relaunched your PR and everything green too, so I merged it. Thanks very much for your contribution!

**Pull request merged**
